# The lowest and highest numbers used in the sequence column type.
# Together these two decide the number of rows generated.
start_id = 0
end_id = 10


[[columns]]
# The sequence column type contains the id number of the row, starting with `start_id` and ending with `end_id`.
type = "sequence"
name = "id"

[[columns]]
# The date column type contains a random UTC date time within the limits set.
type = "date"
name = "date"
date_from = 2020-01-01
date_to = 2024-12-31

[[columns]]
# The word column type contains a randomly generated word.
type = "word"
name = "word"
length_from = 3
length_to = 20

[[columns]]
# The comma-separated column type contains a collection of items from one of the pools, separated by commas.
type = "comma-separated"
name = "words"
pool = "words"
count_from = 1
count_to = 5

[[columns]]
# The comma-separated column type contains a collection of items from one of the pools, separated by commas.
type = "comma-separated"
name = "hierarchical"
pool = "hierarchical"
count_from = 1
count_to = 5

[[columns]]
# The comma-separated column type contains a collection of items from one of the pools, separated by commas.
type = "comma-separated"
name = "references"
pool = "references"
count_from = 0
count_to = 5


[[pools]]
# The words pool type contains randomly generated "words".
type = "words"
name = "words"
# The count values decide how many words to generate.
count_from = 5
count_to = 10
# The word length values decide how many characters each word will contain.
word_length_from = 3
word_length_to = 20

[[pools]]
# The hierarchical pool type contains data with a letter on the top level and a number on the sub level.
type = "hierarchical"
name = "hierarchical"
top_level_from = "A"
top_level_to = "F"
sub_level_from = 1
sub_level_to = 7

[[pools]]
# The references pool type contains all values generated by the id sequence, it is used in columns that connect to other rows.
type = "references"
name = "references"
